// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CommitteeMember: typeof import('./src/components/CommitteeMember.vue')['default']
    Contact: typeof import('./src/components/Contact.vue')['default']
    DiscordEvents: typeof import('./src/components/DiscordEvents.vue')['default']
    Event: typeof import('./src/components/Event.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionButtons: typeof import('./src/components/SectionButtons.vue')['default']
  }
}
